### ISSUE TITLE
[Documentation] Add section of how to add connection properties as dataSourceProperties in the documentation

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-sp#1011]
**Description:**
Previously with Data Analytics Server, a user can add 'connectionProperties' with a datasource configurations to define a list of parameters to be pass when establishing the connection with database. But with the Stream Processor, we are using 'dataSourceProperties' instead of 'connectionProperties' to do the same [1]. For an example,

```
    - name: APIM_ANALYTICS_DB
      description: "The datasource used for APIM statistics aggregated data."
      jndiConfig:
        name: jdbc/APIM_ANALYTICS_DB
      definition:
        type: RDBMS
        configuration:
          jdbcUrl: jdbc:mysql://localhost:3306/testquant1
          username: root
          password: root
          driverClassName: com.mysql.jdbc.Driver                     
          maxPoolSize: 50
          idleTimeout: 60000
          connectionTestQuery: SELECT 1
          validationTimeout: 30000
          isAutoCommit: false
          dataSourceProperties:    
            - name: verifyServerCertificate
              value: 'false' 
            - name: requireSSL
              value: 'false'               
            - name: useSSL
              value: 'false'
```
Here, the each property will pass as 'name' and respective value for each property will pass as 'value' under dataSourceProperties. We need to add this to the documentation [2].

[1] https://github.com/wso2/carbon-datasources/blob/7f766ec0d379dc46a64dfef030c85a4256f8a549/components/org.wso2.carbon.datasource.core/src/test/resources/conf/deployment.yaml#L81-L85
[2] https://docs.wso2.com/display/SP4xx/Configuring+Datasources

**Suggested Labels:**
Type/Documentation

**Affected Product Version:**
Documentation of all SP Versions.
