### ISSUE TITLE
When there are no business rules existed, users with viewer's permission are allowed to click on 'create business rule' button.

### ISSUE THREAD

**Issue by minudika** [wso2/product-sp#414]
**Description:**
When there are no business rules existed, users with viewer's permission are allowed to click on 'create business rule' button.
User is allowed to proceed until selecting 'create from scratch' or 'create from template' options.
But after that user is not allowed to do anything related to creating business rules.

**Suggested Labels:**
Bug

**Suggested Assignees:**
@minudika @senthuran16 

**Affected Product Version:**
4.0.0-beta5 and above

**Steps to reproduce:**
1. In dashboard/deployment.yaml, add following configs under auth.configs.
   ```yaml
    userManager:
    adminRole: role_1
    userStore:
      users:
        -
          user:
            username: admin
            password: YWRtaW4=
            roles: 1
        -
          user:
            username: abc
            password: YWRtaW4=
            roles: 2
        -
          user:
            username: xyz
            password: YWRtaW4=
            roles: 3
        -
          user:
            username: pqr
            password: YWRtaW4=
            roles: 4
        -
          user:
            username: manager
            password: bWFuYWdlcg==
            roles: 5

        -
          user:
            username: viewer
            password: dmlld2Vy
            roles: 6
      roles:
        -
          role:
            id: 1
            displayName: role_1
        -
          role:
            id: 2
            displayName: role_2
        -
          role:
            id: 3
            displayName: role_3
        -
          role:
            id: 4
            displayName: role_4
        -
          role:
            id: 5
            displayName: role_5
        -
          role:
            id: 6
            displayName: role_6
    ```
2. Add following config under wso2.business.rules.manager.
   ```yaml
   roles:
    manager:
      - name: manager
        id: 5
    viewer:
      - name: viewer
        id: 6
   ```
3. Start dashboard runtime.
4. Login with following credentials.
    ```
     username: viewer
     password: admin
    ```
5. Create business rule button should be displayed even though the user is not allowed to create business rules.
