### ISSUE TITLE
Configuring system parameters for Siddhi Extensions has not been documented

### ISSUE THREAD

**Issue by senthuran16** [wso2/product-sp#472]
**Description:**
Way to configure System parameters of a Siddhi extension in the `deployment.yaml` file is not documented.
eg:
For configuring `host` & `port` system parameters of `tcp` extension, the following has to be added in `SPHOME/conf/worker/deployment.yaml`
```
siddhi: 
  extensions: 
    - extension: 
        name: tcp
        namespace: source
        properties: 
          host: 0.0.0.0
          port: 5511
```

**Suggested Labels:**
Documentation

**Suggested Assignees:**
@RukshiW 

**Related Issues:**
https://github.com/wso2-extensions/siddhi-store-rdbms/issues/43

**Comment by Niveathika92** [comment]
@RukshiW A kind reminder on this.

**Comment by RukshiW** [comment]
Please check [1] and let me know if any further corrections are needed.

[1] https://docs.wso2.com/display/SP420/Overriding+System+Parameter+Values+of+an+Extension

**Comment by senthuran16** [comment]
@RukshiW Please do the following corrections.

1. _**Step3**_ should be changed as,

```
siddhi:
    extensions:
        - extension:
```
(The `-` in front of `extension` is missing)

2. _**Step 4**_ says "The archetypes of extensions supported are execution, io, map, script and store". `source` and `sink` are also supported (Usage of `source` is shown in _**Example 1**_).

3. _**Example 2**_ should be changed as, 
```
siddhi:
  extensions:
    - extension:
        name: rdbms
        namespace: store
        properties:
          mysql.batchEnable: true
          mysql.batchSize: 1000
          mysql.indexCreateQuery: "CREATE INDEX {{TABLE_NAME}}_INDEX ON {{TABLE_NAME}} ({{INDEX_COLUMNS}})"
          mysql.recordDeleteQuery: "DELETE FROM {{TABLE_NAME}} {{CONDITION}}"
          mysql.recordExistsQuery: "SELECT 1 FROM {{TABLE_NAME}} {{CONDITION}} LIMIT 1"
```
(`extension` should be mentioned with a `-` in front; and the `name` and `namespace` have to be swapped)

**Comment by RukshiW** [comment]
Did the corrections mentioned in the previous comment by senthuran16.

**Comment by senthuran16** [comment]
@RukshiW Please re-indent _**Example 2**_ as:

```
siddhi:
  extensions:
    - extension:
        name: rdbms
        namespace: store
        properties:
          mysql.batchEnable: true
          mysql.batchSize: 1000
          mysql.indexCreateQuery: "CREATE INDEX {{TABLE_NAME}}_INDEX ON {{TABLE_NAME}} ({{INDEX_COLUMNS}})"
          mysql.recordDeleteQuery: "DELETE FROM {{TABLE_NAME}} {{CONDITION}}"
          mysql.recordExistsQuery: "SELECT 1 FROM {{TABLE_NAME}} {{CONDITION}} LIMIT 1"
```
