### ISSUE TITLE
Changing context path of the dashboard breaks the 'Select data provider' step in 'Create Widget' wizard

### ISSUE THREAD

**Issue by this** [wso2/product-sp#544]
**Description:**
Changing the contaxt path of the Portal webapp (from `/portal` to something else) causes to break the 2nd step of the 'Create Widget' wizard.

**Cause:**
`/portal` is [hard-coded in the `DataProviderAPI`](https://github.com/wso2/carbon-analytics/blob/v2.0.310/components/org.wso2.carbon.data.provider/src/main/java/org/wso2/carbon/data/provider/DataProviderAPI.java#L55) class.

**Affected Product Version:**
sp-4.1.0
**Steps to reproduce:**
1. Add following configuration to `<SP_HOME>/conf/dashboard/deployment.yaml` in order to change the dashboard web apps context path to `/abc`
```yaml
# Carbon UI server configurations
wso2.carbon-ui-server:
  apps:
    # configurations for the Portal app
    "portal":
      contextPath: "/abc"
```
2. Start Sp and log in to the 'portal' webapp
3. Click `+ CREATE WIDGET` button.
4. Enter a name and move to the 2nd step.
5. You will get a blank screen
