### ISSUE TITLE
Distribution sink on 2 node HA doesn't work

### ISSUE THREAD

**Issue by dzatloukal** [wso2/product-sp#570]
**Description:**
I have two SP nodes on different servers in HA cluster. I need to use distributing sinks, because both of nodes consumes events from EI, but passive node hold these events in queue. Active node send events to DB. I used @distribution annotation in tcp sink to distributing events from passive node to active node. Also I set forcePublish property to true, all as is described in documentation. https://docs.wso2.com/display/SP410/Minimum+High+Availability+%28HA%29+Deployment Now I have two problems.

1.
When one of node is down, the active node is still dropping events with this error: Dropping event at Sink 'tcp' at 'DistributionStream' as its still trying to reconnect! Why is there this error, if it's running in HA and one node is still up?

2.
When both nodes are running, passive node still doesn't distribute events to active node, so only half of events are sended to DB, the second half still remainings on passive node and they are published only when passive node change state to active.

**Suggested Labels:**
bug

**Affected Product Version:**
SP 4.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Deploy two siddhi apps on both nodes

`Distributor.siddhi

@sink(type='tcp' , sync='true', @map(type='json'), @distribution(
forcePublish='true',
strategy='broadcast',
@destination(
url='tcp://x.x.x.0:7612/ExecutorSourceStream'),
@destination(
url='tcp://x.x.x.1:7612/ExecutorSourceStream')))
define stream DistributionStream(
test string
);`

`Executor.siddhi

@source(type='tcp', context='ExecutorSourceStream', @map(type='json'))
define stream ExecutorSourceStream(
test string
);`

2. Set deployment.yml config on both nodes
`siddhi: 
extensions: 
- extension: 
    name: tcp
    namespace: source
    properties: 
      host: 0.0.0.0
      port: 7612`
3. Start SP in two node HA on different servers.

**Comment by senthuran16** [comment]
The `forcePublish` keyword is not available in WSO2 SP 4.0.0, so please use [WSO2 SP 4.1.0](https://github.com/wso2/product-sp/releases/tag/v4.1.0) for this purpose.

Also, when configuring the TCP extension in `conf/worker/deployment.yaml` of nodes, include the specific node's host id as `host` under `properties`.
Eg:
If your Node 1's host id is `10.20.30.40`, and Node 2's host id is `10.20.30.41`:

`node_1/conf/worker/deployment.yaml` should have
```
siddhi: 
  extensions: 
    - extension: 
        name: tcp
        namespace: source
        properties: 
          host: 10.20.30.40
          port: 7612
```
And
`node_2/conf/worker/deployment.yaml` should have
```
siddhi: 
  extensions: 
    - extension: 
        name: tcp
        namespace: source
        properties: 
          host: 10.20.30.41
          port: 7612
```
